from deeplabsam.pose.models.target_generators.base import TARGET_GENERATORS, BaseGenerator, SequentialGenerator
from deeplabsam.pose.models.target_generators.heatmap_targets import HeatmapGaussianGenerator, HeatmapPlateauGenerator
